sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.3
    - g++-5.3
    - clang
    - libgtest-dev
    #- wget
    #- ca-certificates #for wget

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5.3" CC="gcc-5.3"; fi
    

script:
    - $CXX --version



