sudo: required
dist: trusty

language: cpp
compiler:
  - clang

before_script:
  - sudo bash ./ci/install-llvm-37-from-repos.sh

script:
    - ls /usr/bin
    - $CXX --version
    - llvm-config --version
    - llvm-config --prefix
    - llvm-config --src-root
    - llvm-config --obj-root
    - llvm-config --bindir
    - llvm-config --includedir
    - llvm-config --libdir
    - llvm-config --cppflags
    - llvm-config --cflags
    - llvm-config --cxxflags
    - llvm-config --ldflags
    - llvm-config --system-libs
    - llvm-config --system-libs
    - llvm-config --libs
    - llvm-config --libnames
    - llvm-config --libfiles
    - llvm-config --components
    - llvm-config --targets-built
    - llvm-config --host-target
    - llvm-config --build-mode
    - llvm-config --assertion-mode



